// online/src/viewer/react/scenecanvas.jsx

import React, { forwardRef } from 'react';

import { LightedTrackballCanvas } from './ltcanvas.jsx';
import { ShapedGeometry } from './geometry.jsx';

const SceneCanvasRef = ( { scene, toolActions, trackball, syncCamera, children3d }, exporterRef ) =>
{
  return (
    <LightedTrackballCanvas lighting={scene.lighting} sceneCamera={ { ...scene.camera } } trackball={trackball}
        syncCamera={syncCamera} toolActions={toolActions} >
      { scene.shapes &&
        <ShapedGeometry ref={exporterRef} embedding={scene.embedding} shapes={scene.shapes} toolActions={toolActions} />
      }
      {children3d}
    </LightedTrackballCanvas>
  );
}

export const SceneCanvas = forwardRef( SceneCanvasRef );

// online/src/app/classic/components/scenecanvas.jsx


import { createEffect } from 'solid-js';
import { LightedTrackballCanvas } from './ltcanvas.jsx';
import { ShapedGeometry } from './geometry.jsx';

const SceneCanvas = ( props ) =>
{
  return (
    <Show when={ () => props.scene?.shapes }>
      <LightedTrackballCanvas toolActions={props.toolActions} height={props.height} width={props.width} >
        <ShapedGeometry embedding={props.scene.embedding} shapes={props.scene?.shapes} toolActions={props.toolActions} />
        {props.children3d}
      </LightedTrackballCanvas>
    </Show> );
}

export { SceneCanvas };
