// online/src/viewer/solid/scenes.jsx

import { createMemo, createSignal } from 'solid-js';

import { Select } from "@kobalte/core";
import UnfoldMoreIcon from "@suid/icons-material/UnfoldMore";
import CheckIcon from '@suid/icons-material/Check';

import { selectScene, useWorkerClient } from '../../workerClient/index.js';

const styles = {
  margin: '1em',
  minWidth: 120,
};

export const SceneMenu = (props) =>
{
  const { state, postMessage } = useWorkerClient();
  const sceneTitles = createMemo( () => state.scenes .map( (scene,index) =>
    scene.title || (( index === 0 )? "default scene" : `scene ${index}`) ) );
  const [ sceneTitle, setSceneTitle ] = createSignal( sceneTitles()[0] );

  const handleChange = (sceneTitle) =>
  {
    setSceneTitle( sceneTitle );
    postMessage( selectScene( sceneTitles() .indexOf( sceneTitle ) ) );
  }

  return (
    <div style={ { position: 'absolute', background: 'lightgray', top: '1em', left: '1em' } }>
      <Select.Root
        value={sceneTitle()}
        onChange={handleChange}
        options={sceneTitles()}
        placeholder="Select a scene…"
        itemComponent={props => (
          <Select.Item item={props.item} class="select__item">
            <Select.ItemLabel>{props.item.rawValue}</Select.ItemLabel>
            <Select.ItemIndicator class="select__item-indicator">
              <CheckIcon />
            </Select.ItemIndicator>
          </Select.Item>
        )}
      >
        <Select.Trigger class="select__trigger" aria-label="Scene">
          <Select.Value class="select__value">
            {state => state.selectedOption()}
          </Select.Value>
          <Select.Icon class="select__icon">
            <UnfoldMoreIcon />
          </Select.Icon>
        </Select.Trigger>
        <Select.Portal mount={props.root}>
          <Select.Content class="select__content">
            <Select.Listbox class="select__listbox" />
          </Select.Content>
        </Select.Portal>
      </Select.Root>
    </div>
  );
}

// online/src/ui/viewer/scenes.jsx

import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { makeStyles } from '@material-ui/core/styles';
import InputLabel from '@material-ui/core/InputLabel';
import FormControl from '@material-ui/core/FormControl';
import Select from '@material-ui/core/Select';

import { selectScene } from './store.js';

const useStyles = makeStyles((theme) => ({
  formControl: {
    margin: theme.spacing(1),
    minWidth: 120,
  },
  selectEmpty: {
    marginTop: theme.spacing(2),
  },
}));

export const SceneMenu = () =>
{
  const scenes = useSelector( state => state.scenes );
  const classes = useStyles();
  const report = useDispatch();
  const [sceneIndex, setSceneIndex] = useState( 0 );
  const handleChange = (event) =>
  {
    const index = event.target.value;
    setSceneIndex( index );
    report( selectScene( index ) );
  }

  return scenes && scenes[1] && (
    <div style={ { position: 'absolute', background: 'lightgray', top: '0px' } }>
      <FormControl variant="outlined" className={classes.formControl}>
        <InputLabel htmlFor="scene-menu-label">Scene</InputLabel>
        <Select
          native
          value={sceneIndex}
          onChange={handleChange}
          label="Scene"
          inputProps={{
            name: 'scene',
            id: 'scene-menu-label',
          }}
        >
          {scenes.map((scene, index) => (
            <option key={index} value={index}>{
              scene.title || (( index === 0 )? "- none -" : `scene ${index}`)
            }</option>)
          )}
        </Select>
      </FormControl>
    </div>
  );
}
