// online/src/viewer/solid/geometry.jsx
import { createEffect, createMemo, createSignal } from "solid-js";
import { Vector3, Matrix4, BufferGeometry, Float32BufferAttribute } from "three";


const Instance = ( props ) =>
{
  let meshRef;
  createEffect( () => {
    const m = new Matrix4();
    m.set( ...props.rotation );
    meshRef.matrix = m;
  } );

  const handleHover = value => e =>
  {
    if ( props.toolActions?.onHover ) {
      e.stopPropagation();
      props.toolActions?.onHover( props.id, props.position, props.type, value );
    }
  }
  const handleClick = ( e ) =>
  {
    if ( props.toolActions?.onClick ) {
      e.stopPropagation()
      props.toolActions?.onClick( props.id, props.position, props.type, props.selected )
    }
  }
  const handlePointerDown = ( e ) =>
  {
    if ( props.toolActions?.onDragStart ) {
      e.stopPropagation()
      props.toolActions?.onDragStart( props.id, props.position, props.type, props.selected, e )
    }
  }
  const emissive = () => props.selected? "#f6f6f6" : "black"
  // TODO: cache materials
  return (
    <group position={ props.position } >
      <mesh matrixAutoUpdate={false} ref={meshRef} geometry={props.geometry} 
          onPointerOver={handleHover(true)} onPointerOut={handleHover(false)} onClick={handleClick}
          onPointerDown={handlePointerDown} >
        <meshLambertMaterial attach="material" color={props.color} emissive={emissive()} />
      </mesh>
    </group>
  )
}

const InstancedShape = ( props ) =>
{
  const geometry = createMemo( () => {
    const { vertices, faces } = props.shape;
    const computeNormal = ( [ v0, v1, v2 ] ) => {
      const e1 = new Vector3().subVectors( v1, v0 )
      const e2 = new Vector3().subVectors( v2, v0 )
      return new Vector3().crossVectors( e1, e2 ).normalize()
    }
    let positions = [];
    let normals = [];
    faces.forEach( face => {
      const corners = face.vertices.map( i => vertices[ i ] )
      const { x:nx, y:ny, z:nz } = computeNormal( corners )
      corners.forEach( ( { x, y, z } ) => {
        positions.push( x, y, z )
        normals.push( nx, ny, nz )
      } )
    } );
    const geometry = new BufferGeometry();
    geometry.setAttribute( 'position', new Float32BufferAttribute( positions, 3 ) );
    geometry.setAttribute( 'normal', new Float32BufferAttribute( normals, 3 ) );
    geometry.computeBoundingSphere();
    return geometry;
  } );

  if ( props.shape.instances.length === 0 )
    return null;
  return (
    <>
      <For each={props.shape.instances}>{ instance =>
        <Instance {...instance} geometry={geometry()} toolActions={props.toolActions} />
      }</For>
    </>
  )
}

export const ShapedGeometry = ( props ) =>
{
  return (
    // <Show when={ () => props.shapes }>
      <group matrixAutoUpdate={false}>
        <For each={Object.values( props.shapes || {} )}>{ shape =>
          <InstancedShape shape={shape} toolActions={props.toolActions} />
        }</For>
      </group>
    // </Show>
  )
};

// online/src/wc/components/geometry.jsx
import { BufferGeometry, Vector3, Float32BufferAttribute, Matrix4 } from 'three'
import React, { useMemo, useRef, useLayoutEffect } from 'react'
import { useInstanceSorter, useEmbedding } from './hooks.js'

const createGeometry = ( { vertices, faces } ) =>
{
  const computeNormal = ( [ v0, v1, v2 ] ) => {
    const e1 = new Vector3().subVectors( v1, v0 )
    const e2 = new Vector3().subVectors( v2, v0 )
    return new Vector3().crossVectors( e1, e2 ).normalize()
  }
  let positions = []
  let normals = []
  faces.forEach( face => {
    const corners = face.vertices.map( i => vertices[ i ] )
    const { x:nx, y:ny, z:nz } = computeNormal( corners )
    corners.forEach( ( { x, y, z } ) => {
      positions.push( x, y, z )
      normals.push( nx, ny, nz )
    })
  } )
  const geometry = new BufferGeometry()
  geometry.setAttribute( 'position', new Float32BufferAttribute( positions, 3 ) )
  geometry.setAttribute( 'normal', new Float32BufferAttribute( normals, 3 ) )
  geometry.computeBoundingSphere()
  return geometry
}

const Instance = ( { id, vectors, position, rotation, geometry, color, selected, highlightBall=()=>{}, onClick, onHover } ) =>
{
  // debugger
  const ref = useRef()
  useLayoutEffect( () => {
    const m = new Matrix4()
    m.set( ...rotation )
    ref.current.applyMatrix4( m )
  }, [rotation] )
  const handleHoverIn = ( e ) =>
  {
    e.stopPropagation()
    onHover && onHover( vectors, true )
  }
  const handleHoverOut = ( e ) =>
  {
    e.stopPropagation()
    onHover && onHover( vectors, false )
  }
  const handleClick = ( e ) =>
  {
    if ( onClick ) { // may be undefined when the model is not editable, or when the object is not clickable in the current mode
      e.stopPropagation()
      onClick && onClick( id, vectors, selected )
    }
  }
  const emissive = selected? "#bbbbbb" : highlightBall( id )? "#884444" : "black"
  // TODO: cache materials
  return (
    <group position={ position } >
      <mesh matrixAutoUpdate={false} ref={ ref } geometry={geometry} onPointerOver={handleHoverIn} onPointerOut={handleHoverOut} onClick={handleClick}>
        <meshLambertMaterial attach="material" color={color} emissive={emissive} />
      </mesh>
    </group>
  )
}

const InstancedShape = ( { instances, shape, onClick, onHover, highlightBall } ) =>
{
  // debugger
  const geometry = useMemo( () => createGeometry( shape ), [ shape ] )
  return (
    <>
      { instances.map( instance => 
        <Instance key={instance.id} {...instance} geometry={geometry} highlightBall={highlightBall} onClick={onClick} onHover={onHover} /> ) }
    </>
  )
}

export const SortedGeometry = ( { sortedInstances, highlightBall, handleClick, onHover } ) =>
{
  return (
    <>
      { sortedInstances.map( ( { shape, instances } ) =>
        <InstancedShape key={shape.id} shape={shape} instances={instances} highlightBall={highlightBall} onClick={handleClick} onHover={onHover} />
      ) }
    </>
  )
}

export const ShapedGeometry = ( { shapes, instances, embedding, highlightBall, handleClick, onHover } ) =>
{
  const sortedInstances = useInstanceSorter( shapes, instances )
  const ref = useEmbedding( embedding )
  return ( sortedInstances &&
    <group matrixAutoUpdate={false} ref={ref}>
      <SortedGeometry {...{ sortedInstances, highlightBall, handleClick, onHover }} />
    </group>
  ) || null
}
